#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 Huawei
# GNU General Public License v3.0+ (see COPYING or
# https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
#     Please read more about how to change this file at
#     https://www.github.com/huaweicloud/magic-modules
#
# ----------------------------------------------------------------------------

from __future__ import absolute_import, division, print_function
__metaclass__ = type

###############################################################################
# Documentation
###############################################################################

ANSIBLE_METADATA = {'metadata_version': '1.1',
                    'status': ["preview"],
                    'supported_by': 'community'}

DOCUMENTATION = '''
---
module: otc_storage_block_volume
description:
    - Represents an Virtual Machine resource.
short_description: Creates a resource of BlockVolume in Opentelekom Cloud
version_added: 2.7
author: Huawei Inc. (@huaweicloud)
requirements:
    - python >= 2.6
    - requests >= 2.18.4
    - keystoneauth1 >= 3.6.0
options:
    state:
        description:
            - Whether the given object should exist in Opentelekom Cloud.
        choices: ['present', 'absent']
        default: 'present'
    name:
        description:
            - the name of volume.
        required: false
    availability_zone:
        description:
            - the availability zone to which the volume belongs.
        required: false
    source_volume_id:
        description:
            - the id of source volume.
        required: false
    snapshot_id:
        description:
            - the id of snapshot.
        required: false
    desc:
        description:
            - the description of volume.
        required: false
    volume_type:
        description:
            - the volume type.
        required: false
    size:
        description:
            - the volume size.
        required: true
    metadata:
        description:
            - the volume metadata.
        required: false
    consistency_group_id:
        description:
            - the id of consistency group.
        required: false
    image_id:
        description:
            - the id of image from which this volume is created.
        required: false
    replica_volume_id:
        description:
            - the id of volume from which this volume is replicated.
        required: false
extends_documentation_fragment: hwc
'''

EXAMPLES = '''
- name: create a block volume
  otc_storage_block_volume:
      identity_endpoint: "{{ identity_endpoint }}"
      user_name: "{{ user_name }}"
      password: "{{ password }}"
      domain_name: "{{ domain_name }}"
      project_name: "{{ project_name }}"
      region: "{{ region }}"
      name: 'ansible_storage_block_volume_test'
      size: 1
      state: present
'''

RETURN = '''
    id:
        description:
            - the uuid of volume.
        returned: success
        type: str
    name:
        description:
            - the name of volume.
        returned: success
        type: str
    attachments:
        description:
            - instance attachment information.
        returned: success
        type: complex
        contains:
            id:
                description:
                    - the uuid of attachment.
                returned: success
                type: str
            server_id:
                description:
                    - the uuid of attached server.
                returned: success
                type: str
            device:
                description:
                    - the corresponding device of attached volume.
                returned: success
                type: str
    availability_zone:
        description:
            - the availability zone to which the volume belongs.
        returned: success
        type: str
    source_volume_id:
        description:
            - the id of source volume.
        returned: success
        type: str
    snapshot_id:
        description:
            - the id of snapshot.
        returned: success
        type: str
    desc:
        description:
            - the description of volume.
        returned: success
        type: str
    volume_type:
        description:
            - the volume type.
        returned: success
        type: str
    size:
        description:
            - the volume size.
        returned: success
        type: int
    metadata:
        description:
            - the volume metadata.
        returned: success
        type: dict
    host:
        description:
            - the host to which the volume belongs.
        returned: success
        type: str
    encrypted:
        description:
            - specify whether the volume is encrypted.
        returned: success
        type: bool
    updated_at:
        description:
            - the time when the volume was updated.
        returned: success
        type: str
    consistency_group_id:
        description:
            - the id of consistency group.
        returned: success
        type: str
    image_id:
        description:
            - the id of image from which this volume is created.
        returned: success
        type: str
    replica_volume_id:
        description:
            - the id of volume from which this volume is replicated.
        returned: success
        type: str
'''

###############################################################################
# Imports
###############################################################################

from ansible.module_utils.hwc_utils import (HwcSession, HwcModule,
                                            DictComparison, navigate_hash,
                                            remove_nones_from_dict,
                                            remove_empty_from_dict)
import json
import re
import time

###############################################################################
# Main
###############################################################################


def main():
    """Main function"""

    module = HwcModule(
        argument_spec=dict(
            state=dict(default='present', choices=['present', 'absent'], type='str'),
            name=dict(type='str'),
            availability_zone=dict(type='str'),
            source_volume_id=dict(type='str'),
            snapshot_id=dict(type='str'),
            desc=dict(type='str'),
            volume_type=dict(type='str'),
            size=dict(required=True, type='int'),
            metadata=dict(type='dict'),
            consistency_group_id=dict(type='str'),
            image_id=dict(type='str'),
            replica_volume_id=dict(type='str')
        )
    )
    session = HwcSession(module, 'storage')

    state = module.params['state']

    if not module.params.get("id"):
        module.params['id'] = get_resource_id(session)

    fetch = get_resource(session)
    changed = False

    if fetch:
        if state == 'present':
            expect = _get_resource_editable_properties(module)
            current_state = response_to_hash(module, fetch)
            if is_different(expect, current_state):
                fetch = update(session, self_link(session), [200])
                fetch = response_to_hash(module, fetch)
                changed = True
            else:
                fetch = current_state
        else:
            delete(session, self_link(session))
            fetch = {}
            changed = True
    else:
        if state == 'present':
            fetch = create(session, collection(session))
            fetch = response_to_hash(module, fetch)
            changed = True
        else:
            fetch = {}

    fetch.update({'changed': changed})

    module.exit_json(**fetch)


def create(session, link, success_codes=None):
    if not success_codes:
        success_codes = [201, 202]
    module = session.module
    r = return_if_object(module, session.post(link, resource_to_create(module)), success_codes)

    complete_states = ['available']
    allowed_states = ['downloading', 'creating', 'available']
    timeout = 60 * int(module.params['timeouts']['create'].rstrip('m'))
    r = wait_for_operation(session, r, timeout, complete_states, allowed_states)
    return r.get('volume')


def update(session, link, success_codes=None):
    if not success_codes:
        success_codes = [201, 202]
    module = session.module
    r = return_if_object(module, session.put(link, resource_to_update(module)), success_codes)

    complete_states = ['available']
    allowed_states = ['downloading', 'creating', 'available']
    timeout = 60 * int(module.params['timeouts']['update'].rstrip('m'))
    r = wait_for_operation(session, r, timeout, complete_states, allowed_states)
    return r.get('volume')


def delete(session, link, success_codes=None):
    if not success_codes:
        success_codes = [202, 204]
    return_if_object(session.module, session.delete(link), success_codes, False)

    timeout = 60 * int(session.module.params['timeouts']['delete'].rstrip('m'))
    wait_for_delete(session, link, timeout)


def fetch_resource(session, link, success_codes=None):
    if not success_codes:
        success_codes = [200]
    return return_if_object(session.module, session.get(link), success_codes)


def get_resource(session):
    link = self_link(session)
    # the link will include Nones if required format parameters are missed
    if re.search('/None/|/None$', link):
        return None

    fetch = fetch_resource(session, link)
    if not fetch:
        return fetch
    return fetch.get('volume')


def link_wrapper(f):
    def _wrapper(session, *args, **kwargs):
        try:
            return f(session, *args, **kwargs)
        except KeyError as ex:
            session.module.fail_json(
                msg="Mapping keys(%s) are not found in generating link" % ex)

    return _wrapper


def get_resource_id(session):
    module = session.module
    link = list_link(session, {'limit': 10, 'marker': '{marker}'})
    p = {'marker': ''}
    v = module.params.get('name')
    ids = set()
    while True:
        r = fetch_resource(session, link.format(**p))
        if r is None:
            break
        r = r.get('volumes', [])
        if r == []:
            break
        for i in r:
            if i.get('name') == v:
                ids.add(i.get('id'))
        if len(ids) >= 2:
            module.fail_json(msg="Multiple resources are found")

        p['marker'] = r[-1].get('id')

    return ids.pop() if ids else None


@link_wrapper
def list_link(session, extra_data=None):
    url = "{endpoint}volumes?limit={limit}&marker={marker}"

    combined = session.module.params.copy()
    if extra_data:
        combined.update(extra_data)

    combined['endpoint'] = session.get_service_endpoint('volumev2')

    return url.format(**combined)


@link_wrapper
def self_link(session):
    url = "{endpoint}volumes/{id}"

    combined = session.module.params.copy()
    combined['endpoint'] = session.get_service_endpoint('volumev2')

    return url.format(**combined)


@link_wrapper
def collection(session):
    url = "{endpoint}volumes"

    combined = session.module.params.copy()
    combined['endpoint'] = session.get_service_endpoint('volumev2')

    return url.format(**combined)


def return_if_object(module, response, success_codes, has_content=True):
    code = response.status_code

    # If not found, return nothing.
    if code == 404:
        return None

    success_codes = [200, 201, 202, 203, 204, 205, 206, 207, 208, 226]
    # If no content, return nothing.
    if code in success_codes and not has_content:
        return None

    result = None
    try:
        result = response.json()
    except getattr(json.decoder, 'JSONDecodeError', ValueError) as inst:
        module.fail_json(msg="Invalid JSON response with error: %s" % inst)

    if code not in success_codes:
        for i in [['message'], ['error', 'message']]:
            msg = navigate_hash(result, i)
            if msg:
                module.fail_json(msg="request failed, %s" % msg)
                break
        else:
            module.fail_json(msg="request failed, return code=%d" % code)

    return result


def is_different(expect, actual):
    # Remove all output-only from actual.
    actual_vals = {}
    for k, v in actual.items():
        if k in expect:
            actual_vals[k] = v

    expect_vals = {}
    for k, v in expect.items():
        if k in actual:
            expect_vals[k] = v

    return DictComparison(expect_vals) != DictComparison(actual_vals)


def resource_to_create(module):
    request = remove_empty_from_dict({
        u'consistencygroup_id': module.params.get('consistency_group_id'),
        u'imageRef': module.params.get('image_id'),
        u'source_replica': module.params.get('replica_volume_id'),
        u'name': module.params.get('name'),
        u'availability_zone': module.params.get('availability_zone'),
        u'source_volid': module.params.get('source_volume_id'),
        u'snapshot_id': module.params.get('snapshot_id'),
        u'description': module.params.get('desc'),
        u'volume_type': module.params.get('volume_type'),
        u'size': module.params.get('size'),
        u'metadata': module.params.get('metadata')
    })
    return {'volume': request}


def resource_to_update(module):
    request = remove_nones_from_dict({
        u'name': module.params.get('name'),
        u'description': module.params.get('desc'),
        u'metadata': module.params.get('metadata')
    })
    return {'volume': request}


def _get_resource_editable_properties(module):
    return remove_nones_from_dict({
        "name": module.params.get("name"),
        "desc": module.params.get("desc"),
        "metadata": module.params.get("metadata"),
    })


# Remove unnecessary properties from the response.
# This is for doing comparisons with Ansible's current parameters.
def response_to_hash(module, response):
    return {
        u'id': response.get(u'id'),
        u'name': response.get(u'name'),
        u'attachments': BlockVolumeAttachmArray(response.get(u'attachments', []), module).from_response(),
        u'availability_zone': response.get(u'availability_zone'),
        u'source_volume_id': response.get(u'source_volid'),
        u'snapshot_id': response.get(u'snapshot_id'),
        u'desc': response.get(u'description'),
        u'volume_type': response.get(u'volume_type'),
        u'size': response.get(u'size'),
        u'metadata': response.get(u'metadata'),
        u'host': response.get(u'os-vol-host-attr:host'),
        u'encrypted': response.get(u'encrypted'),
        u'updated_at': response.get(u'updated_at')
    }


@link_wrapper
def async_op_url(session, extra_data=None):
    url = "{endpoint}volumes/{op_id}"

    combined = session.module.params.copy()
    if extra_data:
        combined.update(extra_data)

    combined['endpoint'] = session.get_service_endpoint('volumev2')

    return url.format(**combined)


def wait_for_operation(session, op_result, timeout, complete_states, allowed_states):
    op_id = navigate_hash(op_result, ['volume', 'id'])
    url = async_op_url(session, {'op_id': op_id})
    return wait_for_completion(session, url, timeout, complete_states, allowed_states)


def wait_for_completion(session, op_uri, timeout, complete_states, allowed_states):
    module = session.module
    end = time.time() + timeout
    while time.time() <= end:
        try:
            op_result = fetch_resource(session, op_uri)
        except Exception:
            time.sleep(1.0)
            continue

        raise_if_errors(op_result, module)

        status = navigate_hash(op_result, ['volume', 'status'])
        if status not in allowed_states:
            module.fail_json(msg="Invalid async operation status %s" % status)
        if status in complete_states:
            return op_result
        time.sleep(1.0)

    module.fail_json(msg="Timeout to wait completion")


def wait_for_delete(session, link, timeout):
    end = time.time() + timeout
    while time.time() <= end:
        try:
            resp = session.get(link)
            if resp.status_code == 404:
                return
        except Exception:
            pass

        time.sleep(1.0)

    session.module.fail_json(msg="Timeout to wait for deletion to be completed")


def raise_if_errors(response, module):
    failed = navigate_hash(response, ['volume', 'code'])
    if failed:
        module.fail_json(msg=navigate_hash(response, ['volume', 'message']))


class BlockVolumeAttachmArray(object):
    def __init__(self, request, module):
        self.module = module
        if request:
            self.request = request
        else:
            self.request = []

    def to_request(self):
        items = []
        for item in self.request:
            items.append(self._request_for_item(item))
        return items

    def from_response(self):
        items = []
        for item in self.request:
            items.append(self._response_from_item(item))
        return items

    def _request_for_item(self, item):
        return {
            u'id': item.get('id'),
            u'server_id': item.get('server_id'),
            u'device': item.get('device')
        }

    def _response_from_item(self, item):
        return {
            u'id': item.get(u'id'),
            u'server_id': item.get(u'server_id'),
            u'device': item.get(u'device')
        }


if __name__ == '__main__':
    main()
